apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deployment6
  labels:
    app: custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: geethaganeshan09/kubecustomservice
        ports:
        - containerPort: 86

---

apiVersion: v1
kind: Service
metadata:
 name: customservice
spec:
 type: NodePort
 ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
 selector:
  app: custom
